source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Specify your gem's dependencies in skillfind_tech.gemspec.
gemspec

group :development do
  gem 'sqlite3'
end
