# frozen_string_literal: true

WARSAWLEASE_ROOT_DOMAIN = ENV['WARSAWLEASE_ROOT_DOMAIN']
SOUNDOFIT_ROOT_DOMAIN = ENV['SOUNDOFIT_ROOT_DOMAIN']

MAPAWYNAJMU_PL_NAME = 'mapawynajmu.pl'
MAPAWYNAJMU_PL_CONSTANTIZED_NAME = 'MapawynajmuPl'
MAPAWYNAJMU_PL_APEX_DOMAIN = 'mapawynajmu.pl'
MAPAWYNAJMU_PL_ROOT_DOMAIN = MAPAWYNAJMU_PL_APEX_DOMAIN
