# frozen_string_literal: true

SOUNDOF_IT_NAME = 'soundof.it'
SOUNDOF_IT_NAME_CONSTANTIZED_NAME = 'SoundofIt'
SOUNDOF_IT_NAME_APEX_DOMAIN = 'soundof.it'
SOUNDOF_IT_NAME_ROOT_DOMAIN = SOUNDOF_IT_NAME_APEX_DOMAIN
SOUNDOF_IT_NAME_LANGS = %i[en].freeze

MAPAWYNAJMU_PL_NAME = 'mapawynajmu.pl'
MAPAWYNAJMU_PL_CONSTANTIZED_NAME = 'MapawynajmuPl'
MAPAWYNAJMU_PL_APEX_DOMAIN = 'mapawynajmu.pl'
MAPAWYNAJMU_PL_ROOT_DOMAIN = MAPAWYNAJMU_PL_APEX_DOMAIN
MAPAWYNAJMU_PL_NAME_LANGS = %i[pl en].freeze

# TODO: Adjust & emove!
WARSAWLEASE_ROOT_DOMAIN = ENV['WARSAWLEASE_ROOT_DOMAIN']
SOUNDOFIT_ROOT_DOMAIN = ENV['SOUNDOFIT_ROOT_DOMAIN']
