default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: primary_dev
  skillfind_tech:
    <<: *default
    database: skillfind_tech_dev
    migrations_paths: db/skillfind_tech_migrate
  mapawynajmu_pl:
    <<: *default
    database: mapawynajmu_pl_dev
    migrations_paths: db/mapawynajmu_pl_migrate

test:
  primary:
    <<: *default
    database: primary_test
  skillfind_tech:
    <<: *default
    database: skillfind_tech_test
  mapawynajmu_pl:
    <<: *default
    database: mapawynajmu_pl_test

production:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  skillfind_tech:
    <<: *default
    url: <%= ENV['HEROKU_POSTGRESQL_GOLD_URL'] %>
  mapawynajmu_pl:
    <<: *default
    url: <%= ENV['HEROKU_POSTGRESQL_BLACK_URL'] %>
