default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: primary_dev
    username: postgres
    password: password
  skillfind_tech:
    <<: *default
    database: skillfind_tech_dev
    username: postgres
    migrations_paths: db/skillfind_tech_migrate
    password: password
  mapawynajmu_pl:
    <<: *default
    database: mapawynajmu_pl_dev
    username: postgres
    migrations_paths: db/mapawynajmu_pl_migrate
    password: password

test:
  primary:
    <<: *default
    database: primary_test
    username: postgres
    password: password
  skillfind_tech:
    <<: *default
    database: skillfind_tech_test
    username: postgres
    password: password
  mapawynajmu_pl:
    <<: *default
    database: mapawynajmu_pl_test
    username: postgres
    password: password

production:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  skillfind_tech:
    <<: *default
    url: <%= ENV['HEROKU_POSTGRESQL_GOLD_URL'] %>
    migrations_paths: db/skillfind_tech_migrate
  mapawynajmu_pl:
    <<: *default
    url: <%= ENV['HEROKU_POSTGRESQL_BLACK_URL'] %>
    migrations_paths: db/mapawynajmu_pl_migrate