default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  soundof_it:
    <<: *default
    database: soundof_it_dev
    migrations_paths: db/soundof_it_migrate
  mapawynajmu_pl:
    <<: *default
    database: mapawynajmu_pl_dev
    migrations_paths: db/mapawynajmu_pl_migrate

test:
  soundof_it:
    <<: *default
    database: soundof_it_test
    migrations_paths: db/soundof_it_migrate
  mapawynajmu_pl:
    <<: *default
    database: mapawynajmu_pl_test
    migrations_paths: db/mapawynajmu_pl_migrate

production:
  soundof_it:
    <<: *default
    url: <%= ENV['HEROKU_POSTGRESQL_GOLD_URL'] %>
    migrations_paths: db/soundof_it_migrate
  mapawynajmu_pl:
    <<: *default
    url: <%= ENV['HEROKU_POSTGRESQL_BLACK_URL'] %>
    migrations_paths: db/mapawynajmu_pl_migrate
