default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: primary_dev
  warsawlease:
    <<: *default
    database: warsawlease_dev
    migrations_paths: db/warsawlease_migrate

test:
  primary:
    <<: *default
    database: primary_test
  warsawlease:
    <<: *default
    database: warsawlease_test
    migrations_paths: db/warsawlease_migrate

production:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  warsawlease:
    <<: *default
    url: <%= ENV['HEROKU_POSTGRESQL_BLACK_URL'] %>
    migrations_paths: db/warsawlease_migrate
