default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  skillfind_tech:
    <<: *default
    database: skillfind_tech_dev
    migrations_paths: db/skillfind_tech_migrate
  mapawynajmu_pl:
    <<: *default
    database: mapawynajmu_pl_dev
    migrations_paths: db/mapawynajmu_pl_migrate

test:
  skillfind_tech:
    <<: *default
    database: skillfind_tech_test
    migrations_paths: db/skillfind_tech_migrate
  mapawynajmu_pl:
    <<: *default
    database: mapawynajmu_pl_test
    migrations_paths: db/mapawynajmu_pl_migrate

production:
  skillfind_tech:
    <<: *default
    url: <%= ENV['HEROKU_POSTGRESQL_GOLD_URL'] %>
    migrations_paths: db/skillfind_tech_migrate
  mapawynajmu_pl:
    <<: *default
    url: <%= ENV['HEROKU_POSTGRESQL_BLACK_URL'] %>
    migrations_paths: db/mapawynajmu_pl_migrate
