development:
  secret_key_base: ac3eb8b837a93eb68727be68506ec6b116b962d3d576a306877fdfd8f283d74f9140048b4e9ef03657e38f73476f12b6f5a9a1e410e8c9608a39e7eed3e4a9be
  verification_code_key: rz6GKZj0wYQyM88lE9MoGpU17pasFANP5Yiyuw7BFiQ
  access_token_key: M7IV/9IDz1dRgcWUBRdiWZEcgnJCOhzUvpWAKeJ0ZVc
  access_token_iv: R+XF0f2+2kEAcygm1H6s3A
  access_token_salt: N0uap3Rx3OzBkLOHIlDxn2jHCAE9e/TflJlmZMaKOgA
  confirmation_token_key: OMWP+gxnxwKBNioiCY6WzC1xA4pylBQd64UBoLTbOMU=
  confirmation_token_iv: EhGepXS6+6WTx8cN3KcrYQ==
  confirmation_token_salt: rDvo1IGVsdClHj1+ccjk2yPfdLY/hcltM56eOk8X5CgnbAWkpjaUY0HYdTkBuOYFzJZXjFdYSWwlWXkGERcXRO7Zp3QREeF6Q0ATJP3eBT6mQH0auJ27sVv3cob6SGoJ0S6x0S/cuEz+a/4ecyaPafGwOxmJwCJKpwOvC2qlHn0=
  password_salt: 6Y96HRyf4SUQJvXchbVnHUGvLlN54n+8dGSz9NozQ78
  aws_access_key_id: '<%= ENV['AWS_ACCESS_KEY_ID'] %>'
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_region: <%= ENV['AWS_REGION'] %>
  aws_bucket: <%= ENV['AWS_BUCKET'] %>

test:
  secret_key_base: ac3eb8b837a93eb68727be68506ec6b116b962d3d576a306877fdfd8f283d74f9140048b4e9ef03657e38f73476f12b6f5a9a1e410e8c9608a39e7eed3e4a9be
  verification_code_key: rz6GKZj0wYQyM88lE9MoGpU17pasFANP5Yiyuw7BFiQ
  access_token_key: M7IV/9IDz1dRgcWUBRdiWZEcgnJCOhzUvpWAKeJ0ZVc
  access_token_iv: R+XF0f2+2kEAcygm1H6s3A
  access_token_salt: N0uap3Rx3OzBkLOHIlDxn2jHCAE9e/TflJlmZMaKOgA
  confirmation_token_key: 9nlMIK9wSytVa/su3UGlyaTUdy5cVAZExxLgmXdnBfE=
  confirmation_token_iv: PtljKi1jSOQ4vXUpUo5Yiw==
  confirmation_token_salt: 9CGe2hVkiD7eb7NQnVKbjqa2Ogmq60sSnSEIcvlXnhc0Ckv23zgL2zHtwCMFtouhHeMPo0NvktUwQK/yKqQrpIsV4Fx/2XdKlOd+GRpHrMdKnab2dEOX4+TO/xPfucxhaKrA7hylS9EFpmwh4kFogAR8FDwdIvpx2w/3UYltycU=
  password_salt: 6Y96HRyf4SUQJvXchbVnHUGvLlN54n+8dGSz9NozQ78

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  verification_code_key: <%= ENV["VERIFICATION_CODE_KEY"] %>
  access_token_key: <%= ENV["ACCESS_TOKEN_KEY"] %>
  access_token_iv: <%= ENV["ACCESS_TOKEN_IV"] %>
  access_token_salt: <%= ENV["ACCESS_TOKEN_SALT"] %>
  confirmation_token_key:  <%= ENV["CONFIRMATION_TOKEN_KEY"] %>
  confirmation_token_iv: <%= ENV["CONFIRMATION_TOKEN_IV"] %>
  confirmation_token_salt: <%= ENV["CONFIRMATION_TOKEN_SALT"] %>
  password_salt: <%= ENV["PASSWORD_SALT"] %>
  aws_access_key_id: '<%= ENV['AWS_ACCESS_KEY_ID'] %>'
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_region: <%= ENV['AWS_REGION'] %>
  aws_bucket: <%= ENV['AWS_BUCKET'] %>
