development:
  secret_key_base: ac3eb8b837a93eb68727be68506ec6b116b962d3d576a306877fdfd8f283d74f9140048b4e9ef03657e38f73476f12b6f5a9a1e410e8c9608a39e7eed3e4a9be
  verification_code_key: rz6GKZj0wYQyM88lE9MoGpU17pasFANP5Yiyuw7BFiQ
  access_token_key: M7IV/9IDz1dRgcWUBRdiWZEcgnJCOhzUvpWAKeJ0ZVc
  access_token_iv: R+XF0f2+2kEAcygm1H6s3A
  access_token_salt: N0uap3Rx3OzBkLOHIlDxn2jHCAE9e/TflJlmZMaKOgA
  password_salt: 6Y96HRyf4SUQJvXchbVnHUGvLlN54n+8dGSz9NozQ78  
  aws_access_key_id: '<%= ENV['AWS_ACCESS_KEY_ID'] %>'
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_region: <%= ENV['AWS_REGION'] %>
  aws_bucket: <%= ENV['AWS_BUCKET'] %>
  mailgun_api_key: <%= ENV['MAILGUN_API_KEY'] %>
  mailgun_api_path: <%= ENV['MAILGUN_API_PATH'] %>
  smslabs_app_key: <%= ENV['SMSLABS_APP_KEY'] %>
  smslabs_secret_key: <%= ENV['SMSLABS_SECRET_KEY'] %>
  emaillabs_secret_key: <%= ENV['EMAILLABS_SECRET_KEY'] %>
  emaillabs_smtp_account: <%= ENV['EMAILLABS_SMTP_ACCOUNT'] %>

test:
  secret_key_base: 723a20f55bef6f6e86b3c3d6b135a5f43a0186c34e12bc408bf985764c871f59bc5cde6dc0a5766ef330d137ad3a9211f5ec83de59ae9f53d921bbee15ce49e1

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  verification_code_key: <%= ENV["VERIFICATION_CODE_KEY"] %>
  access_token_key: <%= ENV["ACCESS_TOKEN_KEY"] %>
  access_token_iv: <%= ENV["ACCESS_TOKEN_IV"] %>
  access_token_salt: <%= ENV["ACCESS_TOKEN_SALT"] %>
  password_salt: <%= ENV["PASSWORD_SALT"] %>
  aws_access_key_id: '<%= ENV['AWS_ACCESS_KEY_ID'] %>'
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_region: <%= ENV['AWS_REGION'] %>
  aws_bucket: <%= ENV['AWS_BUCKET'] %>
  mailgun_api_key: <%= ENV['MAILGUN_API_KEY'] %>
  mailgun_api_path: <%= ENV['MAILGUN_API_PATH'] %>
  smslabs_app_key: <%= ENV['SMSLABS_APP_KEY'] %>
  smslabs_secret_key: <%= ENV['SMSLABS_SECRET_KEY'] %>
  emaillabs_secret_key: <%= ENV['EMAILLABS_SECRET_KEY'] %>
  emaillabs_smtp_account: <%= ENV['EMAILLABS_SMTP_ACCOUNT'] %>
