development:
  secret_key_base: ac3eb8b837a93eb68727be68506ec6b116b962d3d576a306877fdfd8f283d74f9140048b4e9ef03657e38f73476f12b6f5a9a1e410e8c9608a39e7eed3e4a9be
  verification_code_key: rz6GKZj0wYQyM88lE9MoGpU17pasFANP5Yiyuw7BFiQ
  search_token_key: M7IV/9IDz1dRgcWUBRdiWZEcgnJCOhzUvpWAKeJ0ZVc
  search_token_iv: R+XF0f2+2kEAcygm1H6s3A
  search_token_salt: db797db210a7
  access_token_salt: N0uap3Rx3OzBkLOHIlDxn2jHCAE9e/TflJlmZMaKOgA
  email_key: BI8u8QWTe0W9P14g79ZXGabGWMelG/SA+jDpx+NZwJU
  email_salt: 7d29ec67e03d4a73ddff1b59
  password_salt: 6Y96HRyf4SUQJvXchbVnHUGvLlN54n+8dGSz9NozQ78
  phone_body_key: Iq+VplKKv+z0f0lztpa98woDiD9Mjf2w/DP18ClT2AM
  tax_identification_key: vwoupF0kqchmqg3onnYVjG0n74Ri82MpW4vdLhdPhkE
  business_name_key: QzlxHWtUiHUyVtL/+sgRLGqJ2HZjved2PNPxZkMLQrM
  aws_access_key_id: '<%= ENV['AWS_ACCESS_KEY_ID'] %>'
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_region: <%= ENV['AWS_REGION'] %>
  aws_bucket: <%= ENV['AWS_BUCKET'] %>
  mailgun_api_key: <%= ENV['MAILGUN_API_KEY'] %>
  mailgun_api_path: <%= ENV['MAILGUN_API_PATH'] %>
  smslabs_app_key: <%= ENV['SMSLABS_APP_KEY'] %>
  smslabs_secret_key: <%= ENV['SMSLABS_SECRET_KEY'] %>
  emailabs_secret_key: <%= ENV['EMAILLABS_SECRET_KEY'] %>
  emailabs_smtp_account: <%= ENV['EMAILLABS_SMTP_ACCOUNT'] %>

test:
  secret_key_base: 723a20f55bef6f6e86b3c3d6b135a5f43a0186c34e12bc408bf985764c871f59bc5cde6dc0a5766ef330d137ad3a9211f5ec83de59ae9f53d921bbee15ce49e1

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  verification_code_key: <%= ENV["VERIFICATION_CODE_KEY"] %>
  search_token_key: <%= ENV["SEARCH_TOKEN_KEY"] %>
  search_token_iv: <%= ENV["SEARCH_TOKEN_IV"] %>
  search_token_salt: <%= ENV["SEARCH_TOKEN_SALT"] %>
  access_token_salt: <%= ENV["ACCESS_TOKEN_SALT"] %>
  email_key: <%= ENV["EMAIL_KEY"] %>
  email_salt: <%= ENV["EMAIL_SALT"] %>
  password_salt: <%= ENV["PASSWORD_SALT"] %>
  phone_body_key: <%= ENV["PHONE_BODY_KEY"] %>
  tax_identification_key: <%= ENV["TAX_IDENTIFICATION_KEY"] %>
  business_name_key: <%= ENV["BUSINESS_NAME_KEY"] %>
  aws_access_key_id: '<%= ENV['AWS_ACCESS_KEY_ID'] %>'
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_region: <%= ENV['AWS_REGION'] %>
  aws_bucket: <%= ENV['AWS_BUCKET'] %>
  mailgun_api_key: <%= ENV['MAILGUN_API_KEY'] %>
  mailgun_api_path: <%= ENV['MAILGUN_API_PATH'] %>
  smslabs_app_key: <%= ENV['SMSLABS_APP_KEY'] %>
  smslabs_secret_key: <%= ENV['SMSLABS_SECRET_KEY'] %>
  emailabs_secret_key: <%= ENV['EMAILLABS_SECRET_KEY'] %>
  emailabs_smtp_account: <%= ENV['EMAILLABS_SMTP_ACCOUNT'] %>

